- name : Deploying banking application
  hosts : samplenode1
  become: yes
  connection : ssh
  tasks : 
  - name: updating apt
    command : sudo apt-get update

  - name: Deploy Docker Container
    command: docker run -itd -p 8085:8082 suraj838098/medicure-project:1
