apiVersion: apps/v1
kind: Deployment
metadata:
  name: suraj-medicure-deploy
  labels:
    app: healthcare
spec:
  replicas: 3
  selector:
    matchLabels:
      app: healthcare
  template:
    metadata:
      labels:
        app: healthcare
    spec:
      containers:
      - name: suraj-javahealthcare-container
        image: suraj838098/medicure-webapp:v1.0
        ports:
        - containerPort: 8082
---
apiVersion: v1
kind: Service
metadata:
  name: suraj-medicure-np-service
  labels:
    app: healthcare
spec:
  selector:
    app: healthcare

  type: NodePort
  ports:
  - nodePort: 31039
    port: 8082
    targetPort: 8082
